language: python
python:
    - "2.7"
    - "3.3"

env:
    global:
        - PACKAGE="UnitTesting"
    matrix:
        - SUBLIME_TEXT_VERSION="2"
        - SUBLIME_TEXT_VERSION="3"

install:
    - chmod 755 sbin/travis-tool.sh
    - sbin/travis.sh bootstrap $SUBLIME_TEXT_VERSION $PACKAGE

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

script:
    - sbin/travis.sh run_tests $SUBLIME_TEXT_VERSION $PACKAGE

notifications:
    email: false