language: python
python:
    - "2.7"
    - "3.3"

env:
    global:
        - PACKAGE="UnitTesting"
    matrix:
        - SUBLIME_TEXT_VERSION="2"
        - SUBLIME_TEXT_VERSION="3"

install:
    - sh sbin/travis.sh bootstrap

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

script:
    - sh sbin/travis.sh run_tests

notifications:
    email: false